#include <check.h>
#include <math.h>
#include <stdlib.h>
#include <limits.h>
#include "s21_math.h"

TCase *s21_tc_abs(void);
TCase *s21_tc_exp(void);
TCase *s21_tc_fabs(void);
//TCase *s21_tc_acos(void);
//TCase *s21_tc_asin(void);
//TCase *s21_tc_atan(void);
TCase *s21_tc_ceil(void);
TCase *s21_tc_floor(void);
//TCase *s21_tc_fmod(void);
//TCase *s21_tc_log(void);
//TCase *s21_tc_pow(void);
TCase *s21_tc_sin(void);
TCase *s21_tc_cos(void);
TCase *s21_tc_tan(void);
//TCase *s21_tc_sqrt(void);
//TCase *s21_tc_tan(void);
